#!/bin/bash 


printf '\nAdd Stock Biere data\n'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateBiere", "Biere0","Chimay Bleu","200", "123456786", "0.18", "2.1"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateBiere", "Biere1","Chimay Rouge","200", "123456787", "0.19", "2.2"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateBiere", "Biere2","Chimay Dorée","200", "123456788", "0.20", "2.3"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateBiere", "Biere3","Chimay Triple","200", "123456789", "0.21", "2.4"]}'
    

printf '\nAdd Vente data\n'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateVente","Vente0" , "Reduction158", "1578482510" ,"{\"Biere3\" : 12, \"Biere0\" : 3}" ,"11.95"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateVente","Vente1" , "", "1578482510" ,"{\"Biere1\" : 6, \"Biere2\" : 12}" ,"15.95"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateVente","Vente2" , "Reduction45", "1578482510" ,"{\"Biere0\" : 9 }", "11.95"]}'

printf '\nAdd Consigne\n'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateConsigne","Consigne0","Biere0","9"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateConsigne","Consigne1","Biere1","18"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateConsigne","Consigne2","Biere3","12"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateConsigne","Consigne1","Biere1","18"]}'

printf '\nAdd TicketReduction\n'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateTicketDeReduction","TicketReduction0","0.75","111111111110","true"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateTicketDeReduction","TicketReduction1","0.25","111111111111","false"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateTicketDeReduction","TicketReduction2","0.45","111111111112","true"]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin -n chaincode-trappiste -c '{"Args":["updateTicketDeReduction","TicketReduction3","1.75","111111111113","true"]}'


printf '\nAdd Produit for channel-magasin-chimay\n'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin-chimay -n chaincode-trappiste-fournisseur   --peerAddresses peer0.magasin.trappiste.fr:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls/ca.crt --peerAddresses peer0.chimay.fournisseur.be:1001 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chimay.fournisseur.be/peers/peer0.chimay.fournisseur.be/tls/ca.crt -c '{"Args":["putProduit", "Produit01", "123456786", "Chimay Blue", "{\"1\" : \"2.5\",\"100\" : \"2.2\",\"200\" : \"2.1\",\"300\" : \"1.9\"}" ]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin-chimay -n chaincode-trappiste-fournisseur   --peerAddresses peer0.magasin.trappiste.fr:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls/ca.crt --peerAddresses peer0.chimay.fournisseur.be:1001 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chimay.fournisseur.be/peers/peer0.chimay.fournisseur.be/tls/ca.crt -c '{"Args":["putProduit", "Produit02", "123456787", "Chimay Rouge", "{\"1\" : \"2.6\",\"120\" : \"2.3\"}" ]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin-chimay -n chaincode-trappiste-fournisseur   --peerAddresses peer0.magasin.trappiste.fr:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls/ca.crt --peerAddresses peer0.chimay.fournisseur.be:1001 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chimay.fournisseur.be/peers/peer0.chimay.fournisseur.be/tls/ca.crt -c '{"Args":["putProduit", "Produit03", "123456788", "Chimay Dorée", "{\"1\" : \"2.7\",\"90\" : \"2.4\",\"200\" : \"2.2\"}" ]}'
peer chaincode invoke -o orderer0.trappiste.fr:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste.fr/orderers/orderer0.trappiste.fr/msp/tlscacerts/tlsca.trappiste.fr-cert.pem  -C channel-magasin-chimay -n chaincode-trappiste-fournisseur   --peerAddresses peer0.magasin.trappiste.fr:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/magasin.trappiste.fr/peers/peer0.magasin.trappiste.fr/tls/ca.crt --peerAddresses peer0.chimay.fournisseur.be:1001 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chimay.fournisseur.be/peers/peer0.chimay.fournisseur.be/tls/ca.crt -c '{"Args":["putProduit", "Produit04", "123456789", "Chimay Triple", "{\"1\" : \"2.8\",\"300\" : \"2.5\"}" ]}'


sleep 5
printf '\nTest Request for channel-magasin-chimay\n'
peer chaincode query -C channel-magasin-chimay -n chaincode-trappiste-fournisseur -c '{"Args":["getByKey","Produit01"]}'
sleep 5
peer chaincode query -C channel-magasin -n chaincode-trappiste -c '{"Args":["listerBiere"]}'

