#!/bin/bash 


printf '\nadd Stock Biere data\n'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerStock", "Biere0","Chimay Bleu","200", "123456786", "0.18", "2.3"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerStock", "Biere1","Chimay Rouge","200", "123456787", "0.18", "2.3"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerStock", "Biere2","Chimay Dorée","200", "123456788", "0.18", "2.3"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerStock", "Biere3","Chimay Triple","200", "123456789", "0.18", "2.3"]}'
    

printf '\nadd Vente data\n'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerVente","Vente0" , "Reduction158", "1578482510" ,"{\"biere3\" : 12, \"biere0\" : 3}" ,"11.95"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerVente","Vente1" , "", "1578482510" ,"{\"biere1\" : 6, \"biere2\" : 12}" ,"15.95"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerVente","Vente2" , "Reduction45", "1578482510" ,"{\"biere0\" : 9 }", "11.95"]}'

printf '\naddConsigne'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerConsigne","Consigne0","Biere0","9"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerConsigne","Consigne1","Biere1","18"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerConsigne","Consigne2","Biere3","12"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerConsigne","Consigne1","Biere1","18"]}'

printf '\nadd TicketReduction\n'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerTicketDeReduction","TicketReduction0","0.75","111111111110","true"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerTicketDeReduction","TicketReduction1","0.25","111111111111","false"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerTicketDeReduction","TicketReduction2","0.45","111111111112","true"]}'
peer chaincode invoke -o orderer.trappiste-hunter.com:7050 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/trappiste-hunter.com/orderers/orderer.trappiste-hunter.com/msp/tlscacerts/tlsca.trappiste-hunter.com-cert.pem  -C channel-one -n chainecode-trappiste -c '{"Args":["incrementerTicketDeReduction","TicketReduction3","1.75","111111111113","true"]}'